# Data preprocessing

불필요 칼럼제거, 장소명 결측치 제거, 컬럼 정리, 년월 분리

- 장소명, X축,Y축은 folium 팝업 등으로 활용생각.
- 구분은 시설을 구분하여 어떤 시설이 많고, 시설 종류에 따라 주변 유동인구가 어떤 상관관계가 있는지 추측.
- 데이터기준일자는 시계열에 활용되거나 기간별로 방문인구 분석에 쓰일 것이라 생각듬.

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'NanumGothic'

In [2]:
%matplotlib inline

In [3]:
df=pd.read_csv("제주특별자치도_제주도장소(POI)데이터_20151231.csv",encoding='cp949',low_memory=False)

In [4]:
df.head()

,장소 POI에 대한 ID 구분 번호 체계,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,데이터기준일자
0,3,126.568803,33.236546,교통시설,동방파제,제주특별자치도 서귀포시 서귀동 758-2,2015-12-31
1,4,126.562554,33.235071,지명관련,새섬,제주특별자치도 서귀포시 서귀동 산 3-3,2015-12-31
2,5,126.599675,33.230314,지명관련,섶섬,제주특별자치도 서귀포시 보목동 산 1,2015-12-31
3,6,126.565891,33.226031,지명관련,문섬,제주특별자치도 서귀포시 서귀동 산 4,2015-12-31
4,7,126.516395,33.218414,지명관련,범섬,제주특별자치도 서귀포시 법환동 산 2,2015-12-31

In [5]:
df_2 = df.drop(['장소 POI에 대한 ID 구분 번호 체계 '], axis=1)

In [6]:
df_2.head()

    위치좌표 X축값   위치좌표 Y축값     구분   장소명                     소재지     데이터기준일자
0  126.568803  33.236546  교통시설  동방파제  제주특별자치도 서귀포시 서귀동 758-2  2015-12-31
1  126.562554  33.235071  지명관련    새섬  제주특별자치도 서귀포시 서귀동 산 3-3  2015-12-31
2  126.599675  33.230314  지명관련    섶섬    제주특별자치도 서귀포시 보목동 산 1  2015-12-31
3  126.565891  33.226031  지명관련    문섬    제주특별자치도 서귀포시 서귀동 산 4  2015-12-31
4  126.516395  33.218414  지명관련    범섬    제주특별자치도 서귀포시 법환동 산 2  2015-12-31

In [7]:
place_list=df_2['장소명'].unique().tolist()
# place_list

In [8]:
len(df['장소명'].unique().tolist())

65772

In [9]:
df_2=df_2[~df_2['장소명'].isin(['1', '2', '3','4','5','6','7','8','9'])]
df_2

,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,데이터기준일자
0,126.568803,33.236546,교통시설,동방파제,제주특별자치도 서귀포시 서귀동 758-2,2015-12-31
1,126.562554,33.235071,지명관련,새섬,제주특별자치도 서귀포시 서귀동 산 3-3,2015-12-31
2,126.599675,33.230314,지명관련,섶섬,제주특별자치도 서귀포시 보목동 산 1,2015-12-31
3,126.565891,33.226031,지명관련,문섬,제주특별자치도 서귀포시 서귀동 산 4,2015-12-31
4,126.516395,33.218414,지명관련,범섬,제주특별자치도 서귀포시 법환동 산 2,2015-12-31
...,...,...,...,...,...,...
74434,126.542149,33.492701,교육기관,제주CMS에듀케이션,제주특별자치도 제주시 아라이동 3012-7,2015-12-31
74435,126.507533,33.248077,자동차관련,이마트서귀포점전기자동차충전기,제주특별자치도 서귀포시 법환동 841-2,2015-12-31
74436,126.520938,33.517848,자동차관련,이마트제주점전기자동차충전기,제주특별자치도 제주시 삼도이동 1264,2015-12-31
74437,126.282677,33.288644,쇼핑/편의,제주영어마을지에스25,제주특별자치도 서귀포시 대정읍 구억리 산 11,2015-12-31
74438,126.545387,33.477969,자동차관련,현대정비아라점,제주특별자치도 제주시 아라이동 1622-8,2015-12-31

In [10]:
real_list=[]

for i in range(1,1001):
    if str(i) in place_list:
        real_list.append(str(i))

print(real_list)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18']

In [11]:
df_2=df_2[~df_2['장소명'].isin(['10', '11', '12', '13', '14', '15', '16', '17', '18'])]

In [12]:
df_2=df_2[~df_2['장소명'].isin(['-'])]

In [13]:
df_2=df_2[~df_2['장소명'].isin(['N6',
 'N4',
 'N5',
 'N7',
 'S4',
 'S3',
 'S5',
 'N2',
 'N3',
 'N8',
 'N1',
 'S9',
 'S1',
 'S2',
 'S6',
 'S7',
 'S8',
 'E9',
 'N9',
 'E4',
 'E3',
 'E1',
 'E2',
 'E5',
 'E6',
 'E8',
 'E7'])]

In [14]:
# df_2['장소명'].unique().tolist()

In [15]:
pd.set_option('display.max_rows',300)

# df_2.sample(300)

In [16]:
df_2.isnull().sum()

위치좌표 X축값     0
위치좌표 Y축값     0
구분           0
장소명          0
소재지          0
데이터기준일자      0
dtype: int64

In [17]:
df_2['데이터기준일자']

0        2015-12-31
1        2015-12-31
2        2015-12-31
3        2015-12-31
4        2015-12-31
            ...
74434    2015-12-31
74435    2015-12-31
74436    2015-12-31
74437    2015-12-31
74438    2015-12-31
Name: 데이터기준일자, Length: 73760, dtype: object

In [18]:
import pandas as pd
df_2['데이터기준일자'] = pd.to_datetime(df_2['데이터기준일자'], errors='coerce')

In [19]:
df_2['year'] = df_2['데이터기준일자'].dt.year #연도
df_2['month'] = df_2['데이터기준일자'].dt.month #월
df_2['day'] = df_2['데이터기준일자'].dt.day #일
df_2['dayofweek'] = df_2['데이터기준일자'].dt.dayofweek #요일 (월 = 0)

In [20]:
df_2

,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,데이터기준일자,year,month,day,dayofweek
0,126.568803,33.236546,교통시설,동방파제,제주특별자치도 서귀포시 서귀동 758-2,2015-12-31,2015,12,31,3
1,126.562554,33.235071,지명관련,새섬,제주특별자치도 서귀포시 서귀동 산 3-3,2015-12-31,2015,12,31,3
2,126.599675,33.230314,지명관련,섶섬,제주특별자치도 서귀포시 보목동 산 1,2015-12-31,2015,12,31,3
3,126.565891,33.226031,지명관련,문섬,제주특별자치도 서귀포시 서귀동 산 4,2015-12-31,2015,12,31,3
4,126.516395,33.218414,지명관련,범섬,제주특별자치도 서귀포시 법환동 산 2,2015-12-31,2015,12,31,3
...,...,...,...,...,...,...,...,...,...,...
74434,126.542149,33.492701,교육기관,제주CMS에듀케이션,제주특별자치도 제주시 아라이동 3012-7,2015-12-31,2015,12,31,3
74435,126.507533,33.248077,자동차관련,이마트서귀포점전기자동차충전기,제주특별자치도 서귀포시 법환동 841-2,2015-12-31,2015,12,31,3
74436,126.520938,33.517848,자동차관련,이마트제주점전기자동차충전기,제주특별자치도 제주시 삼도이동 1264,2015-12-31,2015,12,31,3
74437,126.282677,33.288644,쇼핑/편의,제주영어마을지에스25,제주특별자치도 서귀포시 대정읍 구억리 산 11,2015-12-31,2015,12,31,3
74438,126.545387,33.477969,자동차관련,현대정비아라점,제주특별자치도 제주시 아라이동 1622-8,2015-12-31,2015,12,31,3

In [21]:
df_2 = df_2.drop(['데이터기준일자'], axis=1)

In [22]:
df_2.to_csv('제주_POI.csv', encoding='cp949', index=False)